# Generated by Django 4.1.4 on 2023-01-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='status',
            field=models.TextField(blank=True, default='Processing', max_length=50, null=True),
        ),
    ]
