# Generated by Django 4.1.4 on 2023-01-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_uploadmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='audio_url',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
