# Generated by Django 4.1.4 on 2023-01-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_uploadmodel_audio_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='mime_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='status',
            field=models.CharField(blank=True, default='Processing', max_length=50, null=True),
        ),
    ]
