# Generated by Django 4.1.7 on 2023-06-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_uploadmodel_download_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('text', models.TextField()),
                ('picture_load', models.FileField(blank=True, null=True, upload_to='file/thumb')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
