# Generated by Django 4.2.16 on 2024-11-24 13:23

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_blogmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
